library(vegan)
library(MASS)
library(cluster.datasets)
library(ggplot2)
dcveg <- read.csv("N:/PARKS/Natural Resources/Monitoring/Transects, Releves, and Photo Monitoring/Archived Monitoring Data/Analyzed Releve Data/RScript/RelData.csv", row.names=1, header = TRUE, sep = ",")
groups <- read.csv("N:/PARKS/Natural Resources/Monitoring/Transects, Releves, and Photo Monitoring/Archived Monitoring Data/Analyzed Releve Data/RScript/Groups.csv", row.names=1, header = TRUE, sep = ",")
ord <- decorana(dcveg)
plot(ord, type = "n")
points(ord, display = "sites", cex = 2, pch = 21, col = "black", bg = "gray")
ordiellipse(ord, groups$Group, display = "sites", kind = "sd", conf = 0.95, draw = "polygon")
sel <- orditorp(ord, dis = "sites", type = "n", col = "blue")
#text(ord, display = "spec", cex = 0.7, col = "red")
sel2 <- orditorp(ord, dis = "spec", cex = 0.7, col = "red")

